name: Steve Auto Deploy

on:
  push:
    branches: master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          cd /home/pratish/steve/
          git pull origin master
          screen -X -S steve quit
          screen -dmS steve bash -c 'python3 /home/pratish/steve/steve.py; exec sh'
          